# -*- coding: utf-8 -*-
"""Flower machine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1soL6NQRwWWKEwrdmfk1VkpD2f7S_oX2R
"""

floweroptions = {
    1: {"name": "Rose", "price": 50},
    2: {"name": "Lilac", "price": 75},
    3: {"name": "Daisy", "price": 80},
    4: {"name": "Sunflower", "price": 95},
    5: {"name": "Lavender", "price": 100}
}

accepted_money = [1, 5, 10, 20, 50, 100]
current_balance = 0


def show_floweroptions():
    print("\n🌸 Flower list:")
    for code, item in floweroptions.items():
        print(f"  {code}. {item['name']} - {item['price']} THB")


def insert_money():
    global current_balance
    while True:
        try:
            money_input = input("Insert money (1,5,10,20,50,100) or 0 to stop: ")
            money = int(money_input)

            if money == 0:
                break
            elif money in accepted_money:
                current_balance += money
                print(f"💰 Current balance: {current_balance} THB")
            else:
                print("❌ Invalid money")
        except ValueError:
            print("❌ Please enter a number")


def select_floweroptions():
    global current_balance

    if current_balance == 0:
        print("⚠️ No money inserted")
        return

    try:
        choice = int(input("Select flower: "))
    except ValueError:
        print("❌ Invalid input")
        return

    if choice not in floweroptions:
        print("❌ Invalid choice")
        return

    product = floweroptions[choice]
    price = product["price"]

    if current_balance >= price:
        current_balance -= price
        print(f"\n🌼 Dispensing: {product['name']}")
        print(f"💵 Change returned: {current_balance} THB")
        current_balance = 0
    else:
        print("⚠️ Insufficient balance")


def flower_machine():
    print("🌸 Welcome to the Flower Machine 🌸")

    while True:
        show_floweroptions()
        insert_money()
        print(f"💰 Your balance: {current_balance} THB")
        select_floweroptions()

        again = input("\nDo you want to buy another flower? (y/n): ").lower()
        if again != 'y':
            print("🙏 Thank you for using our flower machine!")
            break


# Run the machine
flower_machine()